- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/functionalTest/resources/features/F-000/S-000.td.json
- src/main/java/uk/gov/hmcts/reform/judicialbooking/JudicialBookingApplication.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/S2SAuthentication.java
- src/main/resources/liquibase.properties
> Initial chekin to raise the pull request.

- Dockerfile
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
https://tools.hmcts.net/jira/browse/AM-824
Java version upgrade
```
[ ] Yes
[x] No
```
> Java version upgrade

- build.gradle
> Fixing the smoke test.

- build.gradle
- infrastructure/main.tf
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/terraform.tf
- infrastructure/variables.tf
- src/functionalTest/resources/features/F-000/F-000.feature
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/judicialbooking/util/IdamUtils.java
https://tools.hmcts.net/jira/browse/AM-1040
```
[ ] Yes
[X] No
```
> Terraform upgrade changes

- build.gradle
- config/owasp/suppressions.xml
Suppressing the vulnerabilities.
```
[ ] Yes
[x] No
```
> Suppressing the vulnerabilities.

- build.gradle
Upgraded version number for vulnerabilities fixes.
```
[ ] Yes
[x ] No
```
> Vulnerability fix

- charts/am-judicial-booking-service/Chart.yaml
- charts/am-judicial-booking-service/values.aat.template.yaml
- charts/am-judicial-booking-service/values.yaml
- infrastructure/main.tf
- src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeControllerIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/WelcomeController.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/feignclients/DataStoreFeignClient.java
- src/main/resources/application.yaml
- src/main/resources/bootstrap.yml
- src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdviceTest.java
> further cleanup

- .github/workflows/autoupdate.yml
- Jenkinsfile_CNP
- Jenkinsfile_nightly_disabled
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/judicialbooking/befta/JudicialBookingAmTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/AM-1464
Add github autoupdate
```
[ ] Yes
[X] No
```
> Add github autoupdate

- Jenkinsfile_nightly_disabled
- build.gradle
- config/fortify-client.properties
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-1607
Add fortify implementation
```
[ ] Yes
[X] No
```
> Add fortify implementation

- infrastructure/terraform.tf
NA
Fix to resolve missing azuread provider reference
```
[ ] Yes
[X] No
```
> Add azuread provider config

- src/main/resources/application.yaml
Jira link: https://tools.hmcts.net/jira/browse/AM-1666
> Fortify Scan fix for Judicial Service

- infrastructure/terraform.tf
NA
Use azuread version 1.6.0
```
[ ] Yes
[X] No
```
> Fix azuread provider version

- infrastructure/variables.tf
Remove unwanted variables
```
[ ] Yes
[X] No
```
> Remove unwanted vars

- build.gradle
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-1763
Fixing the dependency check errors.
Upgrading the postgres DB version.
```
[ ] Yes
[x] No
```
> Fixing the dependency check errors.

- infrastructure/main.tf
> removing the DB to be able to recreate later with updated schema

- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/AM-1867
Update fortify release ID
```
[ ] Yes
[X] No
```
> Update fortify release ID

- src/functionalTest/resources/features/F-001/F-001.feature
- src/functionalTest/resources/features/F-001/S-004.td.json
- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/model/BookingRequest.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestService.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/util/CorrelationInterceptorUtil.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtil.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestServiceTest.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtilTest.java
userid param for create api
```
[ ] Yes
[ X] No
```
> userid optional param to create api

- src/main/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtil.java
> replacing the UUID check with string check

- build.gradle
- src/contractTest/java/uk.gov.hmcts.reform.judicialbooking/CreateBookingProviderTest.java
- src/contractTest/java/uk.gov.hmcts.reform.judicialbooking/ProviderTestConfiguration.java
- src/contractTest/java/uk.gov.hmcts.reform.judicialbooking/QueryBookingProviderTest.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/BookingOrchestrator.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestServiceTest.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/helper/TestDataBuilder.java
https://tools.hmcts.net/jira/browse/AM-1853
https://tools.hmcts.net/jira/browse/AM-1855
> Judicial Booking Provider Pact Testing

- build.gradle
- src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/BaseTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/SmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/UserTokenProviderConfig.java
https://tools.hmcts.net/jira/browse/AM-1866
Get api smoke test
```
[ ] Yes
[ X] No
```
> Am 1866 smoketest

- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/service/BookingOrchestrator.java
> Am 1857 minorfix

- src/functionalTest/resources/features/F-002/F-002.feature
- src/functionalTest/resources/features/F-002/S-016.td.json
- src/functionalTest/resources/features/common/CreationBaseDataForBookingBeftaUser.td.json
- src/functionalTest/resources/features/common/DeleteDataForBookingsBeftaUser.td.json
https://tools.hmcts.net/jira/browse/AM-1848
AM-1848: Judicial Booking F-002 adding new scenario.
[ ] Yes
[x] No
> AM-1848: Judicial Booking F-002 adding new scenario.

- build.gradle
covarage
```
[ ] Yes
[ X] No
```
> excluding config classes

- gradle/wrapper/gradle-wrapper.properties
> upgrading the gradle version to 6.9

- build.gradle
- [x ] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ x] No
```
> Updated tomcat-embed-core & tomcat-embed-websocket

- charts/am-judicial-booking-service/Chart.yaml
> java upgrade

- charts/am-judicial-booking-service/Chart.yaml
> Updated the chart version

- charts/am-judicial-booking-service/Chart.yaml
> Am 2066 java upgrade

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2067
> Fix CVE-2018-1258

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/BaseTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/judicialbooking/BaseTest.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/util/JacksonUtilsTest.java
https://tools.hmcts.net/jira/browse/AM-2068
Gradle upgrade to 7.4.1
```
[ ] Yes
[ X] No
```
> gradle upgrade to 7.4.1

- build.gradle
> CVE fix jackson Databind dependency

- build.gradle
- config/owasp/suppressions.xml
> CVE fix lang-tag dependency

- .github/workflows/combine-prs.yml
https://tools.hmcts.net/jira/browse/AM-2071
Add combine prs script
```
[ ] Yes
[X] No
```
> Add combine PRs Github Action script

- Dockerfile
- build.gradle
Reverts hmcts/am-judicial-booking-service#263
> Revert "AM-2136: Upgrading to Java 17"

- build.gradle
- config/owasp/suppressions.xml
> Spring update to 5.3.20

- src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/advice/JudicialBookingControllerAdviceTest.java
pitest coverage
```
[ ] Yes
[X ] No
```
> test coverage

- build.gradle
> revert pitest upgrade

- build.gradle
- charts/am-judicial-booking-service/Chart.yaml
- config/owasp/suppressions.xml
> Suppression added

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2279
```
[ ] Yes
[X] No
```
> JBS:Nightly build failures due to CVE issues

- charts/am-judicial-booking-service/Chart.yaml
- charts/am-judicial-booking-service/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/AM-2289
```
[ ] Yes
[X] No
```
> RAS:java version in helm repo version update

- Jenkinsfile_nightly
Enable Ftas in nightly build
```
[ ] Yes
[ X] No
```
> enable fta's in nightly build

- Jenkinsfile_nightly
- security.sh
Nighty build with fta
```
[ ] Yes
[ X] No
```
> nightly build changes

- build.gradle
- docker/database/Dockerfile
- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/AM-2443
jit pack removal to fix build
```
[ ] Yes
[X ] No
```
> Am build fix

- src/main/java/uk/gov/hmcts/reform/judicialbooking/config/AuthCheckerConfiguration.java
fortify scan fix
```
[ ] Yes
[ X] No
```
> fortify fix

- src/integrationTest/java/uk/gov/hmcts/reform/judicialbooking/controller/CreateBookingIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/CreateBookingController.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/model/BookingRequest.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/domain/model/BookingRequestWrapper.java
- src/main/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtil.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/controller/endpoints/CreateBookingControllerTest.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/domain/service/common/ParseRequestServiceTest.java
- src/test/java/uk/gov/hmcts/reform/judicialbooking/util/ValidationUtilTest.java
wrapper for create booking
```
[ ] Yes
[ X] No
```
> wrapper in swagger

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2636
```
[ ] Yes
[X] No
```
> depenency check

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2668
```
[ ] Yes
[X] No
```
> JBS:Application Nightly build failed due to CVE-2022-45688

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2520
Cleanup suppression / CVEs
```
[ ] Yes
[ x] No
```
> Am 2520 cleanup suppressions

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2740
CVE-2023-20860 CVE-2023-20861 suppression
```
[ ] Yes
[x] No
```
> AM-2740 CVE-2023-20861,CVE-2023-20860 Suppression

- security.sh
Reverts hmcts/am-judicial-booking-service#711
> Revert "AM-2742 remove security.sh"

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2786
CVE-2023-20873 Fix
https://tools.hmcts.net/jira/browse/AM-2787
CVE-2023-20862 Fix
```
[ ] Yes
[x] No
```
> AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2816
CVE-2023-28709 tomcat upgraded to 9.0.74
```
[ ] Yes
[x] No
```
> AM-2816 CVE-2023-28709 tomcat upgraded to 9.0.74

- build.gradle
- src/functionalTest/resources/features/F-002/S-012.td.json
- src/functionalTest/resources/features/F-002/S-013.td.json
- src/functionalTest/resources/features/F-002/S-016.td.json
https://tools.hmcts.net/jira/browse/AM-2835
Configure arrays in FTAs so where possible they are unordered
> AM-2835: Configure arrays in FTAs so where possible they are unordered

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2883
CVE-2023-34035 Suppression
```
[ ] Yes
[x] No
```
> AM-2883 CVE-2023-34035 Suppression

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/AM-2883
CVE-2023-34035 spring-security upgraded 6.0.5
```
[ ] Yes
[ x] No
```
> AM-2888 CVE-2023-34035 spring-security upgraded 6.0.5

- build.gradle
https://tools.hmcts.net/jira/browse/AM-2898
Bump HMCTS Java-logging to v6+
```
[ ] Yes
[x] No
```
> AM-2998 Bump HMCTS Java-logging to v6+

- audit.json
https://tools.hmcts.net/jira/browse/AM-2909
Zap Security Scan Failing for V2 URL
```
[ ] Yes
[x] No
```
> AM-2909 Zap Security Scan Failing for V2 URL

- audit.json
https://tools.hmcts.net/jira/browse/AM-2909
10112_Session Management Response Identified igonre added
```
[ ] Yes
[x] No
```
> 10112_Session Management Response Identified igonre added

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/AM-2948
Temp disabling of Security Scan (Zap) in Nightly
> AM-2948 Temp disabling of Security Scan (Zap) in Nightly

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2943
Postgres upgrade to V15 PR No 2
> Am 2943 provision terraform postgres v15 demo 2

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2974
Provision Terraform Postgres v15 ITHC
> AM-2943 Provision Terraform Postgres v15 ITHC

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2994
Provision Terraform Postgres v15 Perftest
> AM-2994 Provision Terraform Postgres v15 Perftest

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2994
provision terraform postgres v15 perftest user host secrets
> Am 2994 provision terraform postgres v15 perftest

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2974
provision terraform postgres v15 ithc user host secrets
> Am 2974 provision terraform postgres v15 ithc

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-2981
Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync
> AM-2981 Connect to v15 JBS ITHC - Remove 'ithc' from git branchesToSync

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-2994
Provision Terraform Postgres v15 - subnet_suffix = "expanded"
> AM-2994 Provision Terraform Postgres v15 - subnet_suffix = "expanded"

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-2974
v15 Provision Expanded Subnet
> Am 2974 v15 provision expanded subnet

- infrastructure/main.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/AM-3019
Provision Terraform Postgres v15 Prod AAT
> AM-3019 Provision Terraform Postgres v15 Prod AAT

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-3019
Provision Terraform v15 server JBS Prod AAT - Resync ITHC branch
> AM-3019 Provision Terraform v15 server JBS Prod AAT - Resync ITHC branch

- build.gradle
https://tools.hmcts.net/jira/browse/AM-3057
PiTest failing in Nightly Mutation Tests pitest gradle plugin bumped to 1.15.0
> AM-2991 pitest gradle plugin bumped to 1.15.0 to try and fix nightly

- build.gradle
https://tools.hmcts.net/jira/browse/AM-3057
PiTest failing in Nightly Mutation Tests
Revert Renovate Pitest Changes
> AM-3057 Revert Renovate Pitest Changes

- infrastructure/main.tf
v15 Reader User Trigger ITHC, Perftest, Demo
> AM-3059 v15 Reader User Trigger ITHC, Perftest, Demo

- renovate.json
https://tools.hmcts.net/jira/browse/AM-3095
Renovate Exclude befta-fw Pre Releases
> AM-3095 Renovate Exclude befta-fw Pre Releases

- charts/am-judicial-booking-service/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSAM-104
Chart-java Upgrade 5.0.4
> DTSAM-104 Chart-java Upgrade 5.0.4

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-16979
> Adding kv_subscription var and setting for aat

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3023
Schema Trigger bumped to 2
> AM-3023 Schema Trigger bumped to 2

- infrastructure/main.tf
v15 Reader User Trigger AAT 4, ITHC, Perftest, Demo
> AM-3059 v15 Reader User Trigger AAT 4, ITHC, Perftest, Demo

- infrastructure/main.tf
v15 Reader User Trigger AAT 5, ITHC, Perftest, Demo
> AM-3059 v15 Reader User Trigger 5 AAT, ITHC, Perftest, Demo

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3143
Disable enable_temp_tablespaces_on_local_ssd in Prod 2
> AM-3143 Disable enable_temp_tablespaces_on_local_ssd in Prod

- infrastructure/main.tf
> AM-3059 Reader User Trigger 6 Prod

- charts/am-judicial-booking-service/Chart.yaml
- charts/am-judicial-booking-service/values.yaml
https://tools.hmcts.net/jira/browse/DTSAM-252
Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled
> DTSAM-252 Helm chart upgrade - chart-java 5.2.0 ,autoscaling disabled

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/AM-3034
Schema Owner Trigger Prod - 5
> AM-3034 Schema Owner Trigger Prod - 5

- infrastructure/main.tf
> AM-3059 Reader User Trigger 7 Prod

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/AM-3044
Decommission V11 DB - Unsync ITHC branch from Master branch
> AM-3044 Decommission V11 DB - Unsync ITHC branch from Master branch

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/AM-3044
Decommission V11 DB ITHC - Enable DB Migration in Jenkins build
> AM-30444 Decommission V11 DB ITHC - Enable DB Migration in Jenkins build

- Jenkinsfile_CNP
Reverts hmcts/am-judicial-booking-service#1063
> Revert "AM-3044 Decommission V11 DB - Unsync ITHC branch from Master branch"

- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/DTSAM-325
Upgrade azurerm to 3.105.0 after V11 Decommission
> DTSAM-325 Upgrade azurerm to 3.105.0 after V11 Decommission

- build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-382
GIT_COMMIT null in Local Build Fix
> Dtsam 382 git commit null local build

- charts/am-judicial-booking-service/Chart.yaml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> CME-392: AM Helm OCI Update - am-judicial-booking-service

- build.gradle
- config/owasp/suppressions.xml
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/DTSAM-843)
> DTSAM-843 FIx the CVE  CVE-2025-24813 tomcat

- config/owasp/suppressions.xml
[
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/DTSAM-867)
Suppress CVE
> DTSAM-867/8 suppress CVE-2025-31650/1

- build.gradle
https://tools.hmcts.net/jira/browse/DTSAM-913
Forify Client upgrade from 1.4.8 to 1.4.9
> DTSAM-913 Fortify client to Upgrade to from 1.4.8 to 1.4.9

- config/owasp/suppressions.xml
[DTSAM-920](https://tools.hmcts.net/jira/browse/DTSAM-920)
Suppress CVE-2025-48734 Detail apache common
> DTSAM-920 CVE-2025-48734 Detail apache common Suppress
